<?php

/**
 * Implements hook_theme().
 */
function ds_login_theme($existing, $type, $theme, $path) {
  $hooks = array();
  $hooks['loginlink'] = array(
    'variables' => array('data' => array()),
    'template' => "templates/loginlink"
  );
  return $hooks;
}

/**
 * Implements hook_block_info().
 */
function ds_login_block_info() {
  $blocks = array();
  $blocks['loginlink'] = array(
    'info' => t('Login en ventana modal'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function ds_login_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'loginlink':
      $block['content'] = theme('loginlink', array('data'=>link_data()));
      break;
  }
  return $block;
}

function link_data(){
  $path = drupal_get_path('module','ds_login');
  //drupal_add_js($path.'/js/login.js');
  return true;
}